/* eslint-disable */
import './display-one'
import './display-two'
import './file'
import './home'
import './like'
import './logo'
import './mail'
import './me'
import './movie'
import './read'
import './settings'
import './tv'
import './want'
